version: '3.9'

services:

  streamlit:
    tty: true
    stdin_open: true
    build:
      context: .
      target: 'development'
    volumes:
      - '.:/app'
    expose:
      - '8501:8501'
    networks:
      - app-tier

networks:
  app-tier:
    external:
      name: backend_app-tier